### ISSUE TITLE
Upgrading to 0.10.2 leads to `exceptiongroup` error

### ISSUE THREAD

**Issue by alexdewar** [realpython/pytest-mypy#150]
After upgrading to v0.10.2 my CI system started failing, giving the following error:

```
Traceback (most recent call last):
  File "/home/alex/code/FINESSE/.venv/bin/pytest", line 5, in <module>
    from pytest import console_main
  File "/home/alex/code/FINESSE/.venv/lib/python3.9/site-packages/pytest/__init__.py", line 5, in <module>
    from _pytest._code import ExceptionInfo
  File "/home/alex/code/FINESSE/.venv/lib/python3.9/site-packages/_pytest/_code/__init__.py", line 2, in <module>
    from .code import Code
  File "/home/alex/code/FINESSE/.venv/lib/python3.9/site-packages/_pytest/_code/code.py", line 60, in <module>
    from exceptiongroup import BaseExceptionGroup
ModuleNotFoundError: No module named 'exceptiongroup'
```

Full output here: https://github.com/ImperialCollegeLondon/FINESSE/pull/58

It appears that the `exceptiongroup` package is not being installed via `poetry`, though it isn't obvious why.

Any ideas?

**Comment by dmtucker** [comment]
This does not appear to be related to pytest-mypy. Please reopen if that's not correct.
